---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-dashboard
  namespace: trivy-dashboard
  labels:
    app.kubernetes.io/name: trivy-dashboard
    app.kubernetes.io/component: dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-exporter
  namespace: trivy-dashboard
  labels:
    app.kubernetes.io/name: trivy-dashboard
    app.kubernetes.io/component: exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-exporter
  labels:
    app.kubernetes.io/name: trivy-dashboard
    app.kubernetes.io/component: exporter
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
      - exposedsecretreports
      - configauditreports
      - rbacassessmentreports
      - infraassessmentreports
      - clustercompliancereports
      - clustervulnerabilityreports
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-exporter
  labels:
    app.kubernetes.io/name: trivy-dashboard
    app.kubernetes.io/component: exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-exporter
subjects:
  - kind: ServiceAccount
    name: trivy-exporter
    namespace: trivy-dashboard
